// @ts-check
import withNuxt from './.nuxt/eslint.config.mjs'

export default withNuxt(
  {
    // Generated by `wrangler types` (pnpm cf-typegen): 15k lines of ambient Cloudflare types that
    // carry their own, now-stale, eslint-disable comments. Not ours to lint.
    ignores: ['worker-configuration.d.ts']
  },
  {
    // That same file declares the global `Env` interface for the D1/R2/KV bindings. It has no
    // exports, so there is no import-style equivalent — the two server files that need it pull it
    // in with `/// <reference path>`, which the rule's default (`path: 'never'`) rejects.
    rules: {
      '@typescript-eslint/triple-slash-reference': ['error', { lib: 'always', path: 'always', types: 'prefer-import' }]
    }
  },
  {
    // The demo entry buttons link to /demo — a nitro server route (mints the demo-role
    // cookie, redirects home), so it's deliberately a plain <a> and can never appear in
    // the Vue routes the link checker validates against.
    files: ['app/pages/index.vue', 'app/pages/labs/login.vue'],
    rules: {
      'link-checker/valid-route': 'off',
      'link-checker/valid-sitemap-link': 'off'
    }
  }
)
